### ISSUE TITLE
Spam features

### ISSUE THREAD

**Issue by Athozus** [mt-mods/mail#102]
Add the following abilities :
- [x] (Un)mark a player as a spammer | Block/mute player (suggested by @OgelGames) #128 
- [x] (Un)mark a single message as a spam #128 
- [x] Detect a message as a potential spam (only caps, words repeated too much) #128

**Comment by OgelGames** [comment]
An option to block/mute a player from sending mail would also be good.

**Comment by S-S-X** [comment]
> An option to block/mute a player from sending mail would also be good.

I would recommend integrating beerchat mute for this when beerchat is installed and only add custom implementation if it is not (if adding at all in that case).

**Comment by Athozus** [comment]
> I would recommend integrating beerchat mute for this when beerchat is installed and only add custom implementation if beerchat isn't available (if adding at all in that case).

The mail setting should be synced to the beerchat one (for example is beerchat from a server). In the settings page, fields should modify also beerchat. That's pretty simple but I wanted to explain how I'm going to proceed.

Clicking on mute field (don't know yet what it's going to be) should invoke a mail own function, and inside this function, it should check for beerchat then edit the setting. Same for getting the muting state, it should first check if beerchat is installed then update muting settings.

**Comment by S-S-X** [comment]
With beerchat pretty much only actual interface is `beerchat.has_player_muted_player(name, other_name)` or `beerchat.allow_private_message(name, target)`. Both of these returns truth and that's it.

I think significant thing here is that beerchat mute is not implemented at single definite location and already has multiple producers (mute implementations / data sources) and consumers (mute lookups).

For example, jailed players are automatically muted unless recipient has deliberately joined jail discussion. Thing is, there's no single definite setting you could ever sync for muting in beerchat.

To create producer (control beerchat muting through mail mod) you'd have to go with `beerchat.register_callback( ... )` probably either with `"before_send_pm"` or `"before_check_muted"` events.

**Comment by Athozus** [comment]
Yes I've already looked a bit at the code of `mute` plugin, so if I had understood it I just have to use `beerchat.has_player_muted_player()`, as you said. I think I will, when saving or getting a setting, check if this setting has a `sync` function (maybe "`transmit`" for giving the new setting to beerchat) then proceed. I will probably use those functions for "`transmit`" function.

**Comment by S-S-X** [comment]
> I think I will, when saving or getting a setting, check if this setting has a `sync` function (maybe "`transmit`" for giving the new setting to beerchat) then proceed. I will probably use those functions for "`transmit`" function.

Not sure what you exactly mean by _sync_ or _transmit_. If you could elaborate a bit how'd you like it work from player/user perspective I might be able to suggest some possible ways to implement it.

Or could maybe just talk about this a bit at [mt-mods modding chat](https://discord.com/channels/905447873402003486/910567024403546183), might help understanding a bit better how you'd like it and what functionality you'd exactly want for this on mail mod side (and possibly on beerchat's side).

**Comment by Athozus** [comment]
What do I mean by those terms (only proposal names) :

* `sync` : other mod (in this case beerchat) -> mail
* `transmit` : mail -> other mod

Because both should have different way to exchanges settings. But this is simple as that. May be in a `util/shared_settings.lua` file, or something like that.

**Comment by S-S-X** [comment]
What would be the exact things you'd like to `sync` and `transfer`?

**Comment by Athozus** [comment]
> What would be the exact things you'd like to `sync` and `transmit`?

* `sync` : get data from beerchat (using functions)
* `transfer` (yes your previous name was better imo) : transfer data to beerchat, eventually select the right action to do (depending on multiple types of mutes in beerchat)
* Both : check if beerchat is present before executing anything.

This is kind of simple for beerchat, however for some optional other mods it might be more complicated.

**Comment by S-S-X** [comment]
> * sync : get data from beerchat (using functions)

If restricting scope to this mail mod issue, what data you think would be needed from beerchat?

> * transfer (yes your previous name was better imo) : transfer data to beerchat, eventually select the right action to do (depending on multiple types of mutes in beerchat)

Again restricting scope to this issue, what data you think would have to be transferred to beerchat and what should it do with this data?

Is this basically about sending sender and recipent name toward beerchat and getting back boolean which tells if sending is allowed? In other words doing `local is_allowed = beerchat.allow_private_message(sender, recipient)`.

Or is this about sending something else that beerchat should store somewhere for later use or somehow use this data for some configuration or something like that?

**Comment by Athozus** [comment]
Yes the setting will be synchronized as you suggested so it will only implement functions to share the setting to beerchat. When any modification is done from the mail side, it is given to beerchat (`transfer`). When the setting is used/checked, it first checks if beerchat has a new version of the setting (`sync`).

**Comment by S-S-X** [comment]
> Yes the setting will be synchronized as you suggested so it will only implement functions to share the setting to beerchat. When any modification is done from the mail side, it is given to beerchat (`transfer`). When the setting is used/checked, it first checks if beerchat has a new version of the setting (`sync`).

Now I think I get it, basically it would be a configuration synchronization between the mods.

However I still don't understand what exactly would have to be synchronized, can you elaborate: what would be the things that needs to be synchronized between the mods? Or is this still something you also have no idea about and needs some planning?
